# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_session_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_session_window(object):
    def setupUi(self, new_session_window):
        new_session_window.setObjectName("new_session_window")
        new_session_window.resize(310, 406)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(new_session_window)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(new_session_window)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.path_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.path_line_edit.setObjectName("path_line_edit")
        self.horizontalLayout_2.addWidget(self.path_line_edit)
        self.path_tool_button = QtWidgets.QToolButton(self.groupBox)
        self.path_tool_button.setObjectName("path_tool_button")
        self.horizontalLayout_2.addWidget(self.path_tool_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.filename_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.filename_line_edit.setObjectName("filename_line_edit")
        self.horizontalLayout.addWidget(self.filename_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(new_session_window)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.accept_button = QtWidgets.QPushButton(new_session_window)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_3.addWidget(self.accept_button)
        self.cancel_button = QtWidgets.QPushButton(new_session_window)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_3.addWidget(self.cancel_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(new_session_window)
        QtCore.QMetaObject.connectSlotsByName(new_session_window)

    def retranslateUi(self, new_session_window):
        _translate = QtCore.QCoreApplication.translate
        new_session_window.setWindowTitle(_translate("new_session_window", "Form"))
        self.groupBox.setTitle(_translate("new_session_window", "Сохранение"))
        self.label.setText(_translate("new_session_window", "Путь"))
        self.path_tool_button.setText(_translate("new_session_window", "..."))
        self.label_2.setText(_translate("new_session_window", "Имя файла"))
        self.groupBox_2.setTitle(_translate("new_session_window", "Единицы"))
        self.radioButton.setText(_translate("new_session_window", "В/м"))
        self.radioButton_2.setText(_translate("new_session_window", "дБмкВ/м"))
        self.radioButton_3.setText(_translate("new_session_window", "Вт/м2"))
        self.accept_button.setText(_translate("new_session_window", "Принять"))
        self.cancel_button.setText(_translate("new_session_window", "Отменить"))
