[tool.poetry]
name = "smef"
version = "0.7.3"
description = "graphical interface for electric field monitoring system"
authors = ["crinitusfeles <crinitusfeles@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
pandas = "*"
PyQt5 = "^5.10"
pyqtgraph = "*"
numpy = "*"
coloredlogs = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "smef/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install poetry && poetry build"
