# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_generator_settings(object):
    def setupUi(self, generator_settings):
        generator_settings.setObjectName("generator_settings")
        generator_settings.resize(277, 254)
        self.verticalLayout = QtWidgets.QVBoxLayout(generator_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.generator_on_button = QtWidgets.QPushButton(generator_settings)
        self.generator_on_button.setObjectName("generator_on_button")
        self.horizontalLayout_2.addWidget(self.generator_on_button)
        self.generator_off_button = QtWidgets.QPushButton(generator_settings)
        self.generator_off_button.setObjectName("generator_off_button")
        self.horizontalLayout_2.addWidget(self.generator_off_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(generator_settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(generator_settings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(generator_settings)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(generator_settings)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.freq_spin_box = QtWidgets.QSpinBox(generator_settings)
        self.freq_spin_box.setObjectName("freq_spin_box")
        self.gridLayout.addWidget(self.freq_spin_box, 0, 1, 1, 1)
        self.power_spin_box = QtWidgets.QSpinBox(generator_settings)
        self.power_spin_box.setObjectName("power_spin_box")
        self.gridLayout.addWidget(self.power_spin_box, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.accept_button = QtWidgets.QPushButton(generator_settings)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.cancel_button = QtWidgets.QPushButton(generator_settings)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(generator_settings)
        QtCore.QMetaObject.connectSlotsByName(generator_settings)

    def retranslateUi(self, generator_settings):
        _translate = QtCore.QCoreApplication.translate
        generator_settings.setWindowTitle(_translate("generator_settings", "Form"))
        self.generator_on_button.setText(_translate("generator_settings", "Вкл"))
        self.generator_off_button.setText(_translate("generator_settings", "Откл"))
        self.label.setText(_translate("generator_settings", "Частота"))
        self.label_2.setText(_translate("generator_settings", "Мощность"))
        self.label_4.setText(_translate("generator_settings", "мВт"))
        self.label_3.setText(_translate("generator_settings", "Гц"))
        self.accept_button.setText(_translate("generator_settings", "Принять"))
        self.cancel_button.setText(_translate("generator_settings", "Отменить"))
